# Mission 1

![](https://i.imgur.com/Ax3pp2A.png)


Create a "fruit" dataframe that reflects the above example **using a list** data structure

[This resource could help you](https://datatofish.com/list-to-dataframe/).

In [1]:
%pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas) (2026.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [5]:
import pandas as pd
data = [[30,21]]
fruit=["Apples","Bananas"]
df = pd.DataFrame(data, columns=fruit)

df

   Apples  Bananas
0      30       21

# Mission 2

Create a "fruit_vendors" dataframe that reflects the below example **using a dictionary** data structure

![](https://i.imgur.com/CHPn7ZF.png)

[This resource could help you.](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.from_dict.html)

In [12]:
from numpy import column_stack
data = {
    "2017 Sales" : [35,21],
    "2018 Sales" : [41,34]
}

m2 = pd.DataFrame.from_dict(data,columns = fruit, orient="index")

m2

            Apples  Bananas
2017 Sales      35       21
2018 Sales      41       34

# Mission 3

Use a loop to display the values from each column in the dataframe from mission 2.

[This resource could help you](https://www.w3schools.com/python/pandas/ref_df_items.asp)

In [7]:
for x, y in m2.items():
  print(x)
  print(y)

Apples
2017 Sales    35
2018 Sales    41
Name: Apples, dtype: int64
Bananas
2017 Sales    21
2018 Sales    34
Name: Bananas, dtype: int64

# Mission 4

Delete the first row of the dataframe from mission 2

[This resource could help you.](https://sparkbyexamples.com/pandas/pandas-drop-first-row-of-dataframe/#google_vignette)

In [16]:
m4 =m2.drop(index=m2.index[0])
m4

            Apples  Bananas
2018 Sales      41       34

# Mission 5

Delete the first column from the dataframe from mission 2.

In [15]:
m5 = m2.drop(columns=m2.columns[0])
m5

            Bananas
2017 Sales       21
2018 Sales       34