# Mission 1

Display the following information [for this dataset](https://raw.githubusercontent.com/justmarkham/pandas-videos/master/data/u.user).
- The last 5 rows
- The first 5 rows
- The type of each column

Note : start coding something by typing `pd.read_csv()` and explore the different options available, especially the `sep` parameter.

In [14]:
import pandas as pd

url = "https://raw.githubusercontent.com/justmarkham/pandas-videos/master/data/u.user"

df = pd.read_csv(url, sep="|",header=None,
    names=["user_id", "age", "gender", "occupation", "zip_code"])

# Last 5 rows
print("5 last rows")
print(df.tail(5))

# First 5 rows
print("5 first rows")
print(df.head(5))

# Type of each column
print("Types")
print(df.dtypes)

5 last rows
     user_id  age gender     occupation zip_code
938      939   26      F        student    33319
939      940   32      M  administrator    02215
940      941   20      M        student    97229
941      942   48      F      librarian    78209
942      943   22      M        student    77841
5 first rows
   user_id  age gender  occupation zip_code
0        1   24      M  technician    85711
1        2   53      F       other    94043
2        3   23      M      writer    32067
3        4   24      M  technician    43537
4        5   33      F       other    15213
Types
user_id        int64
age            int64
gender        object
occupation    object
zip_code      object
dtype: object

# Mission 2

Display the first 10 rows [in the following file](https://raw.githubusercontent.com/justmarkham/pandas-videos/master/data/drinks.csv)

In [17]:
url_m2 = "https://raw.githubusercontent.com/justmarkham/pandas-videos/master/data/drinks.csv"

df_m2 = pd.read_csv(url_m2)

df_m2.head(10)

,country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol,continent
0,Afghanistan,0,0,0,0.0,Asia
1,Albania,89,132,54,4.9,Europe
2,Algeria,25,0,14,0.7,Africa
3,Andorra,245,138,312,12.4,Europe
4,Angola,217,57,45,5.9,Africa
5,Antigua & Barbuda,102,128,45,4.9,North America
6,Argentina,193,25,221,8.3,South America
7,Armenia,21,179,11,3.8,Europe
8,Australia,261,72,212,10.4,Oceania
9,Austria,279,75,191,9.7,Europe

Set the "country" column as the index for the dataframe, using `set_index` method.

In [19]:
df_m2.set_index("country")

,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol,continent
country,,,,,
Afghanistan,0,0,0,0.0,Asia
Albania,89,132,54,4.9,Europe
Algeria,25,0,14,0.7,Africa
Andorra,245,138,312,12.4,Europe
Angola,217,57,45,5.9,Africa
...,...,...,...,...,...
Venezuela,333,100,3,7.7,South America
Vietnam,111,2,1,2.0,Asia
Yemen,6,0,0,0.1,Asia
Zambia,32,19,4,2.5,Africa
Zimbabwe,64,18,4,4.7,Africa

# Mission 3

Access the values of the row for **Zimbabwe** (use the index value)

In [22]:
df_m2.loc[df_m2["country"] == "Zimbabwe"]

,country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol,continent
192,Zimbabwe,64,18,4,4.7,Africa

# Mision 4

Display only the "continent" column value for the country **Zimbabwe**.

In [24]:
df_m2.loc[df_m2["country"] == "Zimbabwe","continent"]

192    Africa
Name: continent, dtype: object

# Mission 5

Rename the columns [of this dataset](https://raw.githubusercontent.com/justmarkham/pandas-videos/master/data/ufo.csv), try using the following 2 different methods to achieve this:
- Setting column names directly when reading the file
- Editing after creating the dataframe ([This resource could be useful](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.rename.html))

In [25]:
import pandas as pd

url = "https://raw.githubusercontent.com/justmarkham/pandas-videos/master/data/ufo.csv"

columns = ["city", "colors_reported", "shape_reported", "state", "time"]

df_m5 = pd.read_csv(url, names=columns, header=0)

df_m5.head()

                   city colors_reported shape_reported state             time
0                Ithaca             NaN       TRIANGLE    NY   6/1/1930 22:00
1           Willingboro             NaN          OTHER    NJ  6/30/1930 20:00
2               Holyoke             NaN           OVAL    CO  2/15/1931 14:00
3               Abilene             NaN           DISK    KS   6/1/1931 13:00
4  New York Worlds Fair             NaN          LIGHT    NY  4/18/1933 19:00

In [26]:
df_m5 = pd.read_csv(url)

df_m5 = df_m5.rename(columns={
    "City": "city",
    "Colors Reported": "colors_reported",
    "Shape Reported": "shape_reported",
    "State": "state",
    "Time": "time"
})

df_m5.head()

                   city colors_reported shape_reported state             time
0                Ithaca             NaN       TRIANGLE    NY   6/1/1930 22:00
1           Willingboro             NaN          OTHER    NJ  6/30/1930 20:00
2               Holyoke             NaN           OVAL    CO  2/15/1931 14:00
3               Abilene             NaN           DISK    KS   6/1/1931 13:00
4  New York Worlds Fair             NaN          LIGHT    NY  4/18/1933 19:00

# Mission 6

Select the first 3 rows and all the columns of the dataframe using iloc

In [29]:
df_m5.iloc[:3]

          city colors_reported shape_reported state             time
0       Ithaca             NaN       TRIANGLE    NY   6/1/1930 22:00
1  Willingboro             NaN          OTHER    NJ  6/30/1930 20:00
2      Holyoke             NaN           OVAL    CO  2/15/1931 14:00

# Mission 7

Achieve the same result as in mission 6 by using loc

In [31]:
df_m5.loc[0:2, :]

          city colors_reported shape_reported state             time
0       Ithaca             NaN       TRIANGLE    NY   6/1/1930 22:00
1  Willingboro             NaN          OTHER    NJ  6/30/1930 20:00
2      Holyoke             NaN           OVAL    CO  2/15/1931 14:00