# Function to automatic merge and fill missing values


## Create the function
You have to create a function which take 2 arguments :
- argument 1 : DataFrame main
- argument 2 : DataFrame opinion

Your function will return a new DataFrame which is the left merge of both DataFrames, and which has no missing values (so your function has to fill them), add new columns (flag, MONTH and DAY), and OPINION should be translated.

So you have to copy each useful code from the previous quests, and integrate it into a function. **This should achieve the same results as the previous quests.**

In [2]:
import pandas as pd

In [40]:
# Chargement des Datasets

link_main = "https://raw.githubusercontent.com/murpi/wilddata/master/quests/weather_main_2018.csv"
link_opinion = "https://raw.githubusercontent.com/murpi/wilddata/master/quests/weather_opinion_2018.csv"
df_main = pd.read_csv(link_main)
df_opinion = pd.read_csv(link_opinion)

In [41]:
# Affichage des premières lignes de df_main
df_main.head()

,DATE,MAX_TEMPERATURE_C,MIN_TEMPERATURE_C,WINDSPEED_MAX_KMH,TEMPERATURE_MORNING_C,TEMPERATURE_NOON_C,TEMPERATURE_EVENING_C,PRECIP_TOTAL_DAY_MM,HUMIDITY_MAX_PERCENT,VISIBILITY_AVG_KM,PRESSURE_MAX_MB,CLOUDCOVER_AVG_PERCENT,HEATINDEX_MAX_C,DEWPOINT_MAX_C,WINDTEMP_MAX_C
0,2018-01-01,12,8,61,9,11,8,8.9,79,9.500,1018,41.750,12,8,7
1,2018-01-02,13,6,26,8,12,13,0.6,96,9.000,1020,87.875,13,12,6
2,2018-01-03,15,10,40,11,12,10,5.5,82,8.500,1017,91.500,15,13,7
3,2018-01-04,14,11,45,14,14,11,0.0,89,10.000,1011,90.125,14,12,10
4,2018-01-05,12,7,21,10,11,8,1.5,85,9.875,1005,62.375,12,10,7

In [18]:
# Affichage des premières lignes de df_opinion
df_opinion.head()

TypeError: Series.apply() missing 1 required positional argument: 'func'

In [5]:
# Affichage du nombre de lignes et de colonnes de df_main
df_main.shape

(365, 15)

In [4]:
# Affichage des informations de df_main
df_main.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 365 entries, 0 to 364
Data columns (total 15 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   DATE                    365 non-null    object
 1   MAX_TEMPERATURE_C       365 non-null    int64
 2   MIN_TEMPERATURE_C       365 non-null    int64
 3   WINDSPEED_MAX_KMH       365 non-null    int64
 4   TEMPERATURE_MORNING_C   365 non-null    int64
 5   TEMPERATURE_NOON_C      365 non-null    int64
 6   TEMPERATURE_EVENING_C   365 non-null    int64
 7   PRECIP_TOTAL_DAY_MM     365 non-null    float64
 8   HUMIDITY_MAX_PERCENT    365 non-null    int64
 9   VISIBILITY_AVG_KM       365 non-null    float64
 10  PRESSURE_MAX_MB         365 non-null    int64
 11  CLOUDCOVER_AVG_PERCENT  365 non-null    float64
 12  HEATINDEX_MAX_C         365 non-null    int64
 13  DEWPOINT_MAX_C          365 non-null    int64
 14  WINDTEMP_MAX_C          365 non-null    int64
dtypes: float64(3), int64(11), object(1)
memory usage: 42.9+ KB

In [15]:
# Nombre de valeurs nulles de df_main
df_main.isna().sum()

DATE                      0
MAX_TEMPERATURE_C         0
MIN_TEMPERATURE_C         0
WINDSPEED_MAX_KMH         0
TEMPERATURE_MORNING_C     0
TEMPERATURE_NOON_C        0
TEMPERATURE_EVENING_C     0
PRECIP_TOTAL_DAY_MM       0
HUMIDITY_MAX_PERCENT      0
VISIBILITY_AVG_KM         0
PRESSURE_MAX_MB           0
CLOUDCOVER_AVG_PERCENT    0
HEATINDEX_MAX_C           0
DEWPOINT_MAX_C            0
WINDTEMP_MAX_C            0
dtype: int64

In [10]:
# Nombre de lignes et de colonnes de df_opinion
df_opinion.shape

(341, 6)

In [14]:
# Nombre de valeurs nulles de df_opinion
df_opinion.isna().sum()

date                    0
WEATHER_CODE_EVENING    0
TOTAL_SNOW_MM           0
UV_INDEX                0
SUNHOUR                 0
OPINION                 0
dtype: int64

In [42]:
# Création d'une fonction merge_and_fill qui prend en paramètre
# deux DataFrame pour les joindre avec un left join sur la colonne de date

from datetime import datetime

def merge_and_fill(DataFrameMain, DataFrameOpinion):
  # MERGE BOTH DATAFRAMES
  NewDataFrame = pd.merge(
    DataFrameMain,
    DataFrameOpinion,
    left_on="DATE",
    right_on="date",
    how="left")

  # FILL IN MISSING VALUES
  # WEATHER_CODE_EVENING => mode
  NewDataFrame['WEATHER_CODE_EVENING'] = NewDataFrame['WEATHER_CODE_EVENING'].fillna(NewDataFrame['WEATHER_CODE_EVENING'].mode()[0])

  # TOTAL_SNOW_MM => moyenne
  NewDataFrame["TOTAL_SNOW_MM"] = NewDataFrame["TOTAL_SNOW_MM"].fillna(NewDataFrame["TOTAL_SNOW_MM"].mean())

  # UV_INDEX => médiane
  NewDataFrame["UV_INDEX"] = NewDataFrame["UV_INDEX"].fillna(NewDataFrame["UV_INDEX"].median())

  # SUNHOUR => bfill
  NewDataFrame["SUNHOUR"] = (NewDataFrame["SUNHOUR"].ffill().bfill())
  # Ajout de la colonne FLAG pour OPINION nulles
  NewDataFrame['flag'] = NewDataFrame['OPINION'].isna()

  # OPINION => remplacer les nuls par "Unknown"
  NewDataFrame["OPINION"] = NewDataFrame["OPINION"].fillna("unknown")

  # Conversion de la colonne DATE au format Datetime
  NewDataFrame['DATE'] = pd.to_datetime(NewDataFrame['DATE'])


  # Création de la colonne MONTH
  NewDataFrame['MONTH'] = NewDataFrame['DATE'].dt.month

  # Création de la colonne DAY
  NewDataFrame['DAY'] = NewDataFrame['DATE'].dt.day

  # Traduction de la colonne OPINION en français (créer une fonction)

  def trad_opinion(opinion) :
    # Add your code here
    if opinion.lower() == "very good" :
      return 'très bien'
    elif opinion.lower() == "good" :
      return 'bien'
    elif opinion.lower() == "not good not bad" :
      return 'pas bon pas mauvais'
    elif opinion.lower() == "bad" :
      return 'mauvais'
    elif opinion.lower() == "very bad" :
      return 'très mauvais'
    elif opinion.lower() == "unknown" :
      return 'inconnu'
    else :
      return opinion

  NewDataFrame['OPINION'] = NewDataFrame['OPINION'].apply(trad_opinion)

  # Return new merged dataframe
  return NewDataFrame

In [43]:
df_2018 = merge_and_fill(df_main, df_opinion)

In [35]:
# Afficher le nombre de lignes et de colonnes de df_2018
df_2018.shape

(365, 24)

In [44]:

# Afficher les premières lignes de df_2018
df_2018.head()

,DATE,MAX_TEMPERATURE_C,MIN_TEMPERATURE_C,WINDSPEED_MAX_KMH,TEMPERATURE_MORNING_C,TEMPERATURE_NOON_C,TEMPERATURE_EVENING_C,PRECIP_TOTAL_DAY_MM,HUMIDITY_MAX_PERCENT,VISIBILITY_AVG_KM,...,WINDTEMP_MAX_C,date,WEATHER_CODE_EVENING,TOTAL_SNOW_MM,UV_INDEX,SUNHOUR,OPINION,flag,MONTH,DAY
0,2018-01-01,12,8,61,9,11,8,8.9,79,9.500,...,7,2018-01-01,113.0,0.0,3.0,5.1,mauvais,False,1,1
1,2018-01-02,13,6,26,8,12,13,0.6,96,9.000,...,6,2018-01-02,122.0,0.0,3.0,3.3,mauvais,False,1,2
2,2018-01-03,15,10,40,11,12,10,5.5,82,8.500,...,7,2018-01-03,122.0,0.0,3.0,3.3,mauvais,False,1,3
3,2018-01-04,14,11,45,14,14,11,0.0,89,10.000,...,10,2018-01-04,116.0,0.0,3.0,3.3,mauvais,False,1,4
4,2018-01-05,12,7,21,10,11,8,1.5,85,9.875,...,7,2018-01-05,116.0,0.0,3.0,6.9,mauvais,False,1,5

In [32]:
# Afficher les informations de df_2018
df_2018.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 365 entries, 0 to 364
Data columns (total 24 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   DATE                    365 non-null    datetime64[ns]
 1   MAX_TEMPERATURE_C       365 non-null    int64
 2   MIN_TEMPERATURE_C       365 non-null    int64
 3   WINDSPEED_MAX_KMH       365 non-null    int64
 4   TEMPERATURE_MORNING_C   365 non-null    int64
 5   TEMPERATURE_NOON_C      365 non-null    int64
 6   TEMPERATURE_EVENING_C   365 non-null    int64
 7   PRECIP_TOTAL_DAY_MM     365 non-null    float64
 8   HUMIDITY_MAX_PERCENT    365 non-null    int64
 9   VISIBILITY_AVG_KM       365 non-null    float64
 10  PRESSURE_MAX_MB         365 non-null    int64
 11  CLOUDCOVER_AVG_PERCENT  365 non-null    float64
 12  HEATINDEX_MAX_C         365 non-null    int64
 13  DEWPOINT_MAX_C          365 non-null    int64
 14  WINDTEMP_MAX_C          365 non-null    int64
 15  date                    341 non-null    object
 16  WEATHER_CODE_EVENING    341 non-null    float64
 17  TOTAL_SNOW_MM           341 non-null    float64
 18  UV_INDEX                341 non-null    float64
 19  SUNHOUR                 341 non-null    float64
 20  OPINION                 341 non-null    object
 21  flag                    365 non-null    bool
 22  MONTH                   365 non-null    int32
 23  DAY                     365 non-null    int32
dtypes: bool(1), datetime64[ns](1), float64(7), int32(2), int64(11), object(2)
memory usage: 63.2+ KB

## Execution with a loop
You will execute your function in a 9 rounds loop, once per year, and agregate this in a new big DataFrame with 24 columns and lots of rows.

In [51]:
# Chaque année entre 2010 et 2018 (inclus) a deux 2 sources : weather_main_YYYY.csv and weather_opinion_YYYY.csv

df_weather = pd.DataFrame()

# Créez la boucle :

for year in range(2010, 2018):

  # Charger les deux datasets et joingez-les grâce à la fonction merge_and_fill
    base_link = "https://raw.githubusercontent.com/murpi/wilddata/master/quests/"
    data_frame_main = pd.read_csv(f"{base_link}weather_main_{year}.csv")
    Data_frame_opinion = pd.read_csv(f"{base_link}weather_opinion_{year}.csv")
    NewDataFrame = merge_and_fill(data_frame_main, Data_frame_opinion)

# Concaténez ce nouveau DataFrame au(x) précédent(s) pour n'obtenir qu'un long DataFrame df_weather
    df_weather = pd.concat([df_weather, NewDataFrame], ignore_index=True)

In [52]:
# Affichage des premières lignes de df_weather
df_weather.head()

,DATE,MAX_TEMPERATURE_C,MIN_TEMPERATURE_C,WINDSPEED_MAX_KMH,TEMPERATURE_MORNING_C,TEMPERATURE_NOON_C,TEMPERATURE_EVENING_C,PRECIP_TOTAL_DAY_MM,HUMIDITY_MAX_PERCENT,VISIBILITY_AVG_KM,...,WINDTEMP_MAX_C,date,WEATHER_CODE_EVENING,TOTAL_SNOW_MM,UV_INDEX,SUNHOUR,OPINION,flag,MONTH,DAY
0,2010-01-01,5,2,19,2,5,3,0.0,86,10.000,...,-1,2010-01-01,119.0,0.0,1.0,5.1,très mauvais,False,1,1
1,2010-01-02,5,-1,6,-1,4,1,0.0,78,10.000,...,2,2010-01-02,116.0,0.0,1.0,8.7,très mauvais,False,1,2
2,2010-01-03,5,1,26,2,4,2,0.3,61,9.875,...,-3,2010-01-03,119.0,0.0,1.0,6.9,très mauvais,False,1,3
3,2010-01-04,1,-4,25,-2,0,-3,0.0,75,10.000,...,-9,2010-01-04,113.0,0.0,1.0,8.7,très mauvais,False,1,4
4,2010-01-05,2,-5,20,-5,1,-4,0.0,71,10.000,...,-10,2010-01-05,113.0,0.0,1.0,8.7,très mauvais,False,1,5

In [56]:
# Création d'une fonction clean qui :
# * crée une colonne FLAG indiquant une valeur manquante
# * convertit la colonne DATE au format datetime
# * traduit l'opinion en français

def clean(DataFrameYear):

  # ALIGN DATAFRAME SHAPE, DATATYPE
  # Colonne FLAG
  DataFrameYear['flag'] = DataFrameYear['OPINION'].isna()

  # Colone DATE
  DataFrameYear['DATE'] = pd.to_datetime(DataFrameYear['DATE'])
  # Colonne OPINION
  def trad_opinion(opinion) :
    # Add your code here
    if opinion.lower() == "very good" :
      return 'très bien'
    elif opinion.lower() == "good" :
      return 'bien'
    elif opinion.lower() == "not good not bad" :
      return 'pas bon pas mauvais'
    elif opinion.lower() == "bad" :
      return 'mauvais'
    elif opinion.lower() == "very bad" :
      return 'très mauvais'
    elif opinion.lower() == "unknown" :
      return 'inconnu'
    else :
      return opinion

  DataFrameYear['OPINION'] = DataFrameYear['OPINION'].apply(trad_opinion)
  # Return new cleaned dataframe
  return DataFrameYear

In [57]:
# On crée une liste de DataFrames pour les années 2019 à 2022 (inclus)

links = {}
for year in range(2019, 2023):
    # Collect both DataFrames each year
    year = str(year)
    links[year] = "https://raw.githubusercontent.com/WildCodeSchool/data-training-resources/main/quests/weather" + year + ".csv"

# Create dataframes from the links to clean
dfs = {}  # Dictionary to store dataframes
for year, link in links.items():
    dfs[year] = pd.read_csv(link)
    dfs[year] = clean(dfs[year])

dfs['2019']

,DATE,MAX_TEMPERATURE_C,MIN_TEMPERATURE_C,WINDSPEED_MAX_KMH,TEMPERATURE_MORNING_C,TEMPERATURE_NOON_C,TEMPERATURE_EVENING_C,PRECIP_TOTAL_DAY_MM,HUMIDITY_MAX_PERCENT,VISIBILITY_AVG_KM,...,WEATHER_CODE_MORNING,WEATHER_CODE_NOON,WEATHER_CODE_EVENING,TOTAL_SNOW_MM,UV_INDEX,SUNHOUR,OPINION,MONTH,DAY,flag
0,2019-01-01,9,4,10,4,7,8,0.2,94,9.000,...,116,143,176,0,1,5.1,très mauvais,1,1,False
1,2019-01-02,8,5,18,7,7,5,0.0,90,9.000,...,119,116,116,0,1,8.7,très mauvais,1,2,False
2,2019-01-03,6,0,18,0,4,3,0.0,88,10.000,...,116,116,116,0,1,8.7,très mauvais,1,3,False
3,2019-01-04,5,-1,15,-1,4,3,0.0,91,10.000,...,116,116,122,0,1,5.1,très mauvais,1,4,False
4,2019-01-05,6,-1,8,-1,4,3,0.0,91,8.000,...,143,116,116,0,1,8.7,très mauvais,1,5,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,2019-12-27,13,10,13,10,12,11,0.0,96,7.375,...,119,143,116,0,1,8.7,pas bon pas mauvais,12,27,False
361,2019-12-28,11,5,12,7,8,8,0.0,93,7.625,...,143,116,116,0,1,6.9,très mauvais,12,28,False
362,2019-12-29,9,2,11,3,6,7,0.0,86,10.000,...,116,116,116,0,1,8.7,très mauvais,12,29,False
363,2019-12-30,12,4,7,5,9,9,0.0,61,10.000,...,113,113,113,0,1,8.7,très mauvais,12,30,False
364,2019-12-31,10,4,13,4,7,9,0.1,94,9.000,...,113,143,119,0,1,8.7,très mauvais,12,31,False

In [60]:
# Concaténez df_weather avec df_2019 à 2022
df_19_22 = pd.concat([dfs['2019'], dfs['2022']], ignore_index=True)

df_19_22

,DATE,MAX_TEMPERATURE_C,MIN_TEMPERATURE_C,WINDSPEED_MAX_KMH,TEMPERATURE_MORNING_C,TEMPERATURE_NOON_C,TEMPERATURE_EVENING_C,PRECIP_TOTAL_DAY_MM,HUMIDITY_MAX_PERCENT,VISIBILITY_AVG_KM,...,TOTAL_SNOW_MM,UV_INDEX,SUNHOUR,OPINION,MONTH,DAY,flag,SUNSET,SUNRISE,TEMPERATURE_NIGHT_C
0,2019-01-01,9,4,10,4,7,8,0.2,94,9.00,...,0,1,5.1,très mauvais,1.0,1.0,False,NaN,NaN,NaN
1,2019-01-02,8,5,18,7,7,5,0.0,90,9.00,...,0,1,8.7,très mauvais,1.0,2.0,False,NaN,NaN,NaN
2,2019-01-03,6,0,18,0,4,3,0.0,88,10.00,...,0,1,8.7,très mauvais,1.0,3.0,False,NaN,NaN,NaN
3,2019-01-04,5,-1,15,-1,4,3,0.0,91,10.00,...,0,1,5.1,très mauvais,1.0,4.0,False,NaN,NaN,NaN
4,2019-01-05,6,-1,8,-1,4,3,0.0,91,8.00,...,0,1,8.7,très mauvais,1.0,5.0,False,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
725,2022-12-27,10,3,19,3,7,8,0.1,78,10.00,...,0,3,6.9,météo très défavorable,NaN,NaN,False,17:23:00,08:52:00,4.0
726,2022-12-28,12,7,35,7,12,12,0.6,95,10.00,...,0,4,6.9,météo défavorable,NaN,NaN,False,17:23:00,08:52:00,7.0
727,2022-12-29,12,8,18,10,12,9,0.6,92,10.00,...,0,3,3.3,météo défavorable,NaN,NaN,False,17:24:00,08:53:00,11.0
728,2022-12-30,15,7,47,11,14,15,3.5,95,9.75,...,0,4,3.3,météo défavorable,NaN,NaN,False,17:25:00,08:53:00,8.0
729,2022-12-31,17,14,32,15,17,15,0.3,84,10.00,...,0,4,8.7,météo correcte,NaN,NaN,False,17:26:00,08:53:00,15.0

In [61]:
# Affichez les premières lignes de df_weather
df_weather.head()

,DATE,MAX_TEMPERATURE_C,MIN_TEMPERATURE_C,WINDSPEED_MAX_KMH,TEMPERATURE_MORNING_C,TEMPERATURE_NOON_C,TEMPERATURE_EVENING_C,PRECIP_TOTAL_DAY_MM,HUMIDITY_MAX_PERCENT,VISIBILITY_AVG_KM,...,WINDTEMP_MAX_C,date,WEATHER_CODE_EVENING,TOTAL_SNOW_MM,UV_INDEX,SUNHOUR,OPINION,flag,MONTH,DAY
0,2010-01-01,5,2,19,2,5,3,0.0,86,10.000,...,-1,2010-01-01,119.0,0.0,1.0,5.1,très mauvais,False,1,1
1,2010-01-02,5,-1,6,-1,4,1,0.0,78,10.000,...,2,2010-01-02,116.0,0.0,1.0,8.7,très mauvais,False,1,2
2,2010-01-03,5,1,26,2,4,2,0.3,61,9.875,...,-3,2010-01-03,119.0,0.0,1.0,6.9,très mauvais,False,1,3
3,2010-01-04,1,-4,25,-2,0,-3,0.0,75,10.000,...,-9,2010-01-04,113.0,0.0,1.0,8.7,très mauvais,False,1,4
4,2010-01-05,2,-5,20,-5,1,-4,0.0,71,10.000,...,-10,2010-01-05,113.0,0.0,1.0,8.7,très mauvais,False,1,5

# Draw a scatterplot
With Date on X-Axis and Max Temperature on Y-axis

The result must have 11 seasonality for the 11 summers/winters alternance.

Utilisez Seaborn ou Plotly Express selon votre préférence

In [64]:
import plotly.express as px

fig = px.scatter(
    df_weather,
    x="DATE",
    y="MAX_TEMPERATURE_C",
    color="OPINION",
    title="MAX TEMPERATURES EVOLUTION",
    labels={
        "DATE": "Date",
        "MAX_TEMPERATURE_C": "Maximum temperatures",
        "OPINION": "OPINION"
    }
)

fig.show()


Find appropriate dataviz to answer to this question :

Which year had the best weather? Are years very different or not ?

In [66]:
opinion_scores = {
    "très mauvais": 1,
    "mauvais": 2,
    "pas bon pas mauvais": 3,
    "bien": 4,
    "très bien": 5
}

df_weather["OPINION_SCORE"] = df_weather["OPINION"].map(opinion_scores)

df_weather["YEAR"] = pd.to_datetime(df_weather["DATE"]).dt.year

yearly_weather = df_weather.groupby("YEAR")["OPINION_SCORE"].mean().reset_index()

fig = px.bar(
    yearly_weather,
    x="YEAR",
    y="OPINION_SCORE",
    title="Average weather opinion by year",
    labels={
        "YEAR": "Year",
        "OPINION_SCORE": "Average weather score"
    }
)

fig.show()