In [1]:
import pandas as pd

### Welcome to the Apply Challenge

In [3]:
link = 'https://raw.githubusercontent.com/chriszapp/datasets/main/books.csv'
books = pd.read_csv(link, nrows = 13)
books.head()

,bookID,title,authors,average_rating,isbn,isbn13,language_code,num_pages,ratings_count,text_reviews_count,publication_date,publisher
0,1,Harry Potter and the Half-Blood Prince (Harry ...,J.K. Rowling/Mary GrandPré,4.57,0439785960,9780439785969,eng,652,2095690,27591,9/16/2006,Scholastic Inc.
1,2,Harry Potter and the Order of the Phoenix (Har...,J.K. Rowling/Mary GrandPré,4.49,0439358078,9780439358071,eng,870,2153167,29221,9/1/2004,Scholastic Inc.
2,4,Harry Potter and the Chamber of Secrets (Harry...,J.K. Rowling,4.42,0439554896,9780439554893,eng,352,6333,244,11/1/2003,Scholastic
3,5,Harry Potter and the Prisoner of Azkaban (Harr...,J.K. Rowling/Mary GrandPré,4.56,043965548X,9780439655484,eng,435,2339585,36325,5/1/2004,Scholastic Inc.
4,8,Harry Potter Boxed Set Books 1-5 (Harry Potte...,J.K. Rowling/Mary GrandPré,4.78,0439682584,9780439682589,eng,2690,41428,164,9/13/2004,Scholastic

In [ ]:
# Firstly, have a look at the dataset

In [4]:
# Mission 1: use apply to create a new column called 'reviews_opinion': if the ratings is between 4.5 and 5, the reviews_opinion is 'very good';
# if the rating is between 4 and 4.5, the reviews_opinion is 'good'; if the rating is between 3 and 4, the reviews_opinions will be 'neutral';
# if the rating is up to 3 the reviews_opinion is going to be 'bad'

# Add your code here
def get_opinion(rating) :
  if rating >= 4.5 :
    return "very good"
  elif rating >= 4 :
    return 'good'
  elif rating >= 3 :
    return 'neutral'
  else :
    return 'bad'

books["reviews_opinion"] = books["average_rating"].apply(get_opinion)

books[["average_rating", "reviews_opinion"]]

    average_rating reviews_opinion
0             4.57       very good
1             4.49            good
2             4.42            good
3             4.56       very good
4             4.78       very good
5             3.74         neutral
6             4.73       very good
7             4.38            good
8             4.38            good
9             4.22            good
10            4.22            good
11            4.38            good
12            4.21            good

In [16]:
# Mission 2: using apply with a function, create a column with the number of authors per book
# (note that in the column 'authors', each name of the author is divided with the character '/')

# Add your code here
def count_authors (authors) :
  list_authors = authors.split("/")
  return len(list_authors)

books["authors_count"] = books["authors"].apply(count_authors)

print(books[["authors", "authors_count"]])

                       authors  authors_count
0   J.K. Rowling/Mary GrandPré              2
1   J.K. Rowling/Mary GrandPré              2
2                 J.K. Rowling              1
3   J.K. Rowling/Mary GrandPré              2
4   J.K. Rowling/Mary GrandPré              2
5       W. Frederick Zimmerman              1
6                 J.K. Rowling              1
7                Douglas Adams              1
8                Douglas Adams              1
9                Douglas Adams              1
10   Douglas Adams/Stephen Fry              2
11               Douglas Adams              1
12                 Bill Bryson              1

In [17]:
# Mission 3: rewrite the same task as Mission 2 using the lamdba function

books["authors_count"] = books["authors"].apply(
    lambda authors: len(authors.split("/"))
)

print(books[["authors", "authors_count"]])

                       authors  authors_count
0   J.K. Rowling/Mary GrandPré              2
1   J.K. Rowling/Mary GrandPré              2
2                 J.K. Rowling              1
3   J.K. Rowling/Mary GrandPré              2
4   J.K. Rowling/Mary GrandPré              2
5       W. Frederick Zimmerman              1
6                 J.K. Rowling              1
7                Douglas Adams              1
8                Douglas Adams              1
9                Douglas Adams              1
10   Douglas Adams/Stephen Fry              2
11               Douglas Adams              1
12                 Bill Bryson              1

In [18]:
# Mission 4: create a column 'comment_ration'.
# Use the columns 'ratings_count' and 'text_reviews_count' to calculate the percentage of how many text review per reviews are per book:
# percentage = text / reviews * 100
# Use the mathematical operations between columns

books["comment_ration"] = (
    books["text_reviews_count"]
    / books["ratings_count"]
    * 100
)

books[["ratings_count", "text_reviews_count", "comment_ration"]]

    ratings_count  text_reviews_count  comment_ration
0         2095690               27591        1.316559
1         2153167               29221        1.357117
2            6333                 244        3.852834
3         2339585               36325        1.552626
4           41428                 164        0.395868
5              19                   1        5.263158
6           28242                 808        2.860987
7            3628                 254        7.001103
8          249558                4080        1.634890
9            4930                 460        9.330629
10           1266                 253       19.984202
11           2877                 195        6.777894
12         248558                9396        3.780204

In [20]:
# Mission 5: obtain the same result of Mission 4 using apply with a function.
# Try both methods to apply to the whole dataset and apply to selected columns

def calculate_comment_ratio(row):
    return row["text_reviews_count"] / row["ratings_count"] * 100

books["comment_ration"] = books.apply(
    calculate_comment_ratio,
    axis=1
)

books[["ratings_count", "text_reviews_count", "comment_ration"]]

books["comment_ration"] = books[
    ["text_reviews_count", "ratings_count"]
].apply(calculate_comment_ratio, axis=1)


books[["ratings_count", "text_reviews_count", "comment_ration"]]

    ratings_count  text_reviews_count  comment_ration
0         2095690               27591        1.316559
1         2153167               29221        1.357117
2            6333                 244        3.852834
3         2339585               36325        1.552626
4           41428                 164        0.395868
5              19                   1        5.263158
6           28242                 808        2.860987
7            3628                 254        7.001103
8          249558                4080        1.634890
9            4930                 460        9.330629
10           1266                 253       19.984202
11           2877                 195        6.777894
12         248558                9396        3.780204

In [21]:
# Mission 6: obtain the same result of Mission 5 using apply lambda
# Try both methods to apply to the whole dataset and apply to selected columns

books["comment_ration"] = books.apply(
    lambda row: row["text_reviews_count"] / row["ratings_count"] * 100,
    axis=1
)
books[["ratings_count", "text_reviews_count", "comment_ration"]]

books["comment_ration"] = books[
    ["text_reviews_count", "ratings_count"]
].apply(
    lambda row: row["text_reviews_count"] / row["ratings_count"] * 100,
    axis=1
)
books[["ratings_count", "text_reviews_count", "comment_ration"]]

    ratings_count  text_reviews_count  comment_ration
0         2095690               27591        1.316559
1         2153167               29221        1.357117
2            6333                 244        3.852834
3         2339585               36325        1.552626
4           41428                 164        0.395868
5              19                   1        5.263158
6           28242                 808        2.860987
7            3628                 254        7.001103
8          249558                4080        1.634890
9            4930                 460        9.330629
10           1266                 253       19.984202
11           2877                 195        6.777894
12         248558                9396        3.780204

In [24]:
# Mission 7: extract the year from the publication_date column. How many years of publications are recorded in this dataset? Which are them?
books["publication_year"] = (
    books["publication_date"].str[-4:].astype(int)
)

years = sorted(books["publication_year"].unique())

print("Years:", years)
print("Number of different years:", len(years))

books[["title", "publication_date", "publication_year"]]

Years: [np.int64(1996), np.int64(2002), np.int64(2003), np.int64(2004), np.int64(2005), np.int64(2006)]
Number of different years: 6

,title,publication_date,publication_year
0,Harry Potter and the Half-Blood Prince (Harry ...,9/16/2006,2006
1,Harry Potter and the Order of the Phoenix (Har...,9/1/2004,2004
2,Harry Potter and the Chamber of Secrets (Harry...,11/1/2003,2003
3,Harry Potter and the Prisoner of Azkaban (Harr...,5/1/2004,2004
4,Harry Potter Boxed Set Books 1-5 (Harry Potte...,9/13/2004,2004
5,"Unauthorized Harry Potter Book Seven News: ""Ha...",4/26/2005,2005
6,Harry Potter Collection (Harry Potter #1-6),9/12/2005,2005
7,The Ultimate Hitchhiker's Guide: Five Complete...,11/1/2005,2005
8,The Ultimate Hitchhiker's Guide to the Galaxy ...,4/30/2002,2002
9,The Hitchhiker's Guide to the Galaxy (Hitchhik...,8/3/2004,2004
10,The Hitchhiker's Guide to the Galaxy (Hitchhik...,3/23/2005,2005
11,The Ultimate Hitchhiker's Guide (Hitchhiker's ...,1/17/1996,1996
12,A Short History of Nearly Everything,9/14/2004,2004